name: update 

permissions:
  contents: write
  
on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'

jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install packages
      run: pip install jupyter lxml pandas requests regex numpy beautifulsoup4
    - name: Run scraper
      run: jupyter nbconvert --to notebook --execute scraper.ipynb --inplace --ExecutePreprocessor.timeout=600
    - name: Commit changes
      run: |
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        git diff --staged --quiet || git commit -m "Latest data: $(date -u)"
        git push
